In [1]:
import sklearn

In [2]:
sklearn.__version__ 

'0.24.2'

In [4]:
from sklearn.datasets import load_iris

In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [6]:
import pandas as pd

In [17]:
iris = load_iris(as_frame = True)

In [18]:
type(iris)

sklearn.utils.Bunch

In [19]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [23]:
iris_df = iris["data"]

In [25]:
iris_target = iris.target

In [22]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [52]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                 iris.target,
                                                 test_size=0.2)

In [53]:
X_train,X_test,y_train,y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 53                 5.5               2.3                4.0               1.3
 23                 5.1               3.3                1.7               0.5
 123                6.3               2.7                4.9               1.8
 18                 5.7               3.8                1.7               0.3
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 11                 4.8               3.4                1.6               0.2
 75                 6.6               3.0                4.4               1.4
 84                 5.4               3.0                4.5               1.5
 33                 5.5               4.2                1.4               0.2
 55                 5.7               2.8                4.5               1.3
 
 [120 rows x 4 columns],
      sepal length (cm)  

In [54]:
type(X_train)

pandas.core.frame.DataFrame

In [55]:
dt_clf = DecisionTreeClassifier(random_state = 11)

In [56]:
dt_clf.fit(X_train,y_train)          # fit = 학습.

DecisionTreeClassifier(random_state=11)

In [57]:
pred = dt_clf.predict(X_test)

In [58]:
pred

array([2, 0, 2, 2, 1, 0, 2, 0, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 2, 2, 2, 1,
       2, 0, 1, 1, 0, 0, 2, 2])

In [59]:
y_test

118    2
7      0
105    2
113    2
138    2
43     0
131    2
20     0
66     1
95     1
19     0
62     1
92     1
25     0
96     1
48     0
121    2
45     0
148    2
102    2
120    2
93     1
103    2
3      0
56     1
80     1
12     0
47     0
117    2
116    2
Name: target, dtype: int32

In [60]:
from sklearn.metrics import accuracy_score

In [61]:
accuracy_score(y_test,pred)

0.9666666666666667

In [64]:
def test1(a,b):
    '''
    이 함수는 결과값이 3개로 나갑니다.
    '''
    return a+b, a-b, a*b

In [63]:
test1()

NameError: name 'test1' is not defined

In [65]:
result = test1(1,2)

# 과적합 참조
![과적합](과적합.png)

```
print('hello')
```

In [66]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [67]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [84]:
kfold = KFold(n_splits = 5, shuffle = True)

In [85]:
cv_accuracy=[]

In [86]:
iris.data.shape

(150, 4)

In [87]:
kfold = KFold(n_splits = 5, shuffle = True)
n_iter = 0
for train_index, test_index in kfold.split(iris.data):
    print(train_index)
    print('-'*50)
    print(test_index)
    print()
    X_train, X_test = iris.data[train_index], iris.data[test_index]
   # print(X_train, X_test)
    y_train,y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    n_iter +=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 :{X_train.shape[0]}, 검증데이터 건수:{X_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

[  0   1   2   3   5   6   9  12  13  14  16  17  18  19  20  21  22  23
  25  26  27  28  29  30  31  32  35  36  37  38  39  40  42  43  44  45
  49  50  51  52  54  55  57  58  59  60  61  62  63  64  65  68  69  71
  72  73  74  75  76  77  78  79  80  82  83  84  85  86  88  89  91  92
  93  94  95  96  98  99 100 101 102 103 104 105 107 109 110 111 112 113
 114 115 116 118 120 121 122 123 125 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 145 146 148 149]
--------------------------------------------------
[  4   7   8  10  11  15  24  33  34  41  46  47  48  53  56  66  67  70
  81  87  90  97 106 108 117 119 124 126 144 147]

1번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9
[  1   2   4   6   7   8  10  11  12  14  15  16  17  18  19  20  22  23
  24  26  27  29  30  31  33  34  35  36  37  39  40  41  43  44  45  46
  47  48  50  51  53  54  55  56  57  58  59  61  62  63  64  65  66  67
  69  70  71  72  73  74  77  78  79  80  81  82  83  85  86  87  88  89
 

In [102]:
skfold = StratifiedKFold(n_splits = 5, shuffle = False) # 교차검증을 할 때 활용
n_iter = 0
for train_index, test_index in kfold.split(iris.data, iris.target):
    print(train_index)
    print('-'*50)
    print(test_index)
    print()
    X_train, X_test = iris.data[train_index], iris.data[test_index]
   # print(X_train, X_test)
    y_train,y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    n_iter +=1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 :{X_train.shape[0]}, 검증데이터 건수:{X_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

[  0   2   3   4   5   6   8   9  10  13  14  15  16  17  19  20  21  22
  23  24  25  26  27  31  32  33  34  35  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  60  61  62  64  67
  68  69  70  71  74  75  76  77  78  79  80  82  83  84  86  87  88  90
  91  92  93  94  95  96  97  98  99 101 102 103 104 105 107 108 109 110
 112 113 114 115 116 117 120 121 122 123 126 127 128 129 133 134 135 136
 137 138 140 141 142 143 144 145 146 147 148 149]
--------------------------------------------------
[  1   7  11  12  18  28  29  30  36  37  59  63  65  66  72  73  81  85
  89 100 106 111 118 119 124 125 130 131 132 139]

1번째 교차검증
학습데이터 건수 :120, 검증데이터 건수:30
정확도:0.9333333333333333
[  1   2   4   6   7   8   9  11  12  13  14  16  17  18  19  20  22  23
  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  43  44  45
  48  49  50  54  55  56  57  58  59  60  62  63  64  65  66  68  71  72
  73  74  75  76  77  78  80  81  82  83  84  85  86  87  8

In [98]:
kfold = KFold(n_splits = 5, shuffle = True)
n_iter = 0
cv_accuracy=[]
for train_index, test_index in kfold.split(iris.data):
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train,y_test = iris.target[train_index], iris.target[test_index]
    #print(type(pd.Series(y_train)))
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    42
2    40
1    38
dtype: int64
검증용데이터 분포:
 1    12
2    10
0     8
dtype: int64
학습용데이터 분포:
 1    44
0    38
2    38
dtype: int64
검증용데이터 분포:
 0    12
2    12
1     6
dtype: int64
학습용데이터 분포:
 2    43
1    39
0    38
dtype: int64
검증용데이터 분포:
 0    12
1    11
2     7
dtype: int64
학습용데이터 분포:
 0    42
1    39
2    39
dtype: int64
검증용데이터 분포:
 1    11
2    11
0     8
dtype: int64


In [99]:
from sklearn.model_selection import StratifiedKFold               # 비율에 따라 분리.

In [100]:
skfold = StratifiedKFold(n_splits = 5, shuffle = False)             # 셔플을 false하고 비율에 따라 분리했다.
n_iter = 0
cv_accuracy=[]
for train_index, test_index in skfold.split(iris.data, iris.target): # iris.target의 비율을 보고 나누는 것.
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train,y_test = iris.target[train_index], iris.target[test_index]
     #print(type(pd.Series(y_train)))
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64


In [101]:
skfold = StratifiedKFold(n_splits = 5, shuffle = True)             # 셔플을 True로 바꿔봐도 차이는 없다.
n_iter = 0
cv_accuracy=[]
for train_index, test_index in skfold.split(iris.data, iris.target):
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train,y_test = iris.target[train_index], iris.target[test_index]
     #print(type(pd.Series(y_train)))
    print('학습용데이터 분포:\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n',pd.Series(y_test).value_counts())

학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포:
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포:
 0    10
1    10
2    10
dtype: int64


In [109]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [110]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [113]:
scores = cross_val_score(dt_clf,
                iris_data.data,
                iris_data.target,
                scoring = 'accuracy',
                cv = 3)       # estimater , data , target 순서대로.

In [114]:
import numpy as np
print('교차 검증별 정확도', scores)
print('평균 교차 검증 정확도', np.mean(scores))

교차 검증별 정확도 [0.98 0.94 0.98]
평균 교차 검증 정확도 0.9666666666666667


In [119]:
from sklearn.model_selection import GridSearchCV, train_test_split
import pandas as pd

In [116]:
grid_param = {'max_depth' :[1,2,3],
             'min_samples_split':[2,3]}

In [117]:
iris = load_iris()                                              # GridSearchCV = 내가 원하는 값을 볼때까지, 파라미터를 하나씩 조정해가면서 구하는 것.
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2,
                                                    random_state=121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree,
                          param_grid = grid_param,
                          cv=3,
                          refit=True)      # refit = 모두 학습을 시키고나서, 최적의 경우로 학습.
grid_dtree.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [118]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.00033323, 0.00033466, 0.00033299, 0.00033418, 0.00033196,
        0.0003314 ]),
 'std_fit_time': array([0.00047126, 0.00047328, 0.00047092, 0.00047261, 0.00046946,
        0.00046867]),
 'mean_score_time': array([0.00032854, 0.00033498, 0.        , 0.        , 0.        ,
        0.00033593]),
 'std_score_time': array([0.00046463, 0.00047373, 0.        , 0.        , 0.        ,
        0.00047508]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'max_depth': 3, 'min_sample

In [122]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000333      0.000471         0.000329        0.000465   
1       0.000335      0.000473         0.000335        0.000474   
2       0.000333      0.000471         0.000000        0.000000   
3       0.000334      0.000473         0.000000        0.000000   
4       0.000332      0.000469         0.000000        0.000000   
5       0.000331      0.000469         0.000336        0.000475   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [123]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [124]:
scores_df[['params',
           'mean_test_score',
           'rank_test_score',
           'split0_test_score',
           'split1_test_score',
           'split2_test_score'
           ]]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [125]:
grid_dtree.best_score_

0.975

In [126]:
grid_dtree.best_index_

4

In [129]:
pred = grid_dtree.best_estimator_.predict(X_test)

In [130]:
from sklearn.metrics import accuracy_score

In [131]:
print('best estimator 정확도', accuracy_score(y_test,pred))

best estimator 정확도 0.9666666666666667


In [132]:
from sklearn.preprocessing import LabelEncoder

In [133]:
items = ['TV', '냉장고', ' 전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [135]:
encoder = LabelEncoder()
encoder.fit(items) # 정보를 수집해서, 중복 빼고, 숫자를 붙여주는 작업.
labels = encoder.transform(items)

In [138]:
labels

array([1, 2, 0, 5, 4, 4, 3, 3])

In [139]:
encoder.classes_

array([' 전자레인지', 'TV', '냉장고', '믹서', '선풍기', '컴퓨터'], dtype='<U6')

In [140]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', ' 전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'],
      dtype='<U6')

In [141]:
from sklearn.preprocessing import OneHotEncoder

In [142]:
items = ['TV', '냉장고', ' 전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [143]:
encoder = LabelEncoder()
encoder.fit_transform(items)
labels

array([1, 2, 0, 5, 4, 4, 3, 3])

In [146]:
labels = labels.reshape(-1, 1)
labels.shape

(8, 1)

In [163]:
oh_encoder = OneHotEncoder(sparse=True)
oh_labels = oh_encoder.fit_transform(labels)

In [164]:
oh_encoder.categories_

[array([0, 1, 2, 3, 4, 5])]

In [165]:
oh_encoder.sparse

True

In [166]:
oh_encoder

OneHotEncoder()

In [170]:
oh_labels.toarray()

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [172]:
df = pd.DataFrame({'item':['TV', '냉장고', ' 전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [173]:
df

item
0      TV
1     냉장고
2   전자레인지
3     컴퓨터
4     선풍기
5     선풍기
6      믹서
7      믹서

In [177]:
pd.get_dummies(df).values

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]], dtype=uint8)